services:
  rpp-app:
    build: .
    container_name: py-rpp
    image: py-rpp:latest
    ports:
      - "8000:8000"
    environment:
      - RPP_CONFIG_FILE=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml:ro
